name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
 - ferrywlto
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to fill out this bug report!
 - type: textarea
   id: what-happened
   attributes:
     label: What happened?
     description: Also tell us, what did you expect to happen?
     placeholder: Tell us what you see!
   validations:
     required: true
 - type: textarea
   id: expected
   attributes:
     label: Expected behaviour
     description: What should be the expected behavior?
   validations:
     required: true
 - type: textarea
   id: cause
   attributes:
     label: Root Cause Analysis
     description: Why is this happening?
     placeholder: Good for retrospection.
   validations:
     required: true     
 - type: dropdown
   id: severity
   attributes:
     label: How severe of this bug?
     options:
       - P0 (Critical, system wide failure/security)
       - P1 (Severe, some users not able to use)
       - P2 (Serious, some features are not available)
       - P3 (Normal, gitches that can tolerate) 
   validations:
     required: true
